/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Procedimientos.Instancias;
import Procedimientos.Usuariocomdisco;
import Procedimientos.Usuariocompeli;
import javax.swing.DefaultListModel;

/**
 *
 * @author Kevin
 */
public class CompraPelicula extends javax.swing.JDialog {

    /**
     * Creates new form CompraPelicula
     */
    public static DefaultListModel modelopeli;
    Usuariocompeli table = new Usuariocompeli();

    public CompraPelicula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Comprar Disco");
        busnombrepeli.setVisible(false);
        busaupeli.setVisible(false);
        precio1.setVisible(false);
        precio2.setVisible(false);
        alabelpeli.setVisible(false);
        
        modelopeli = new DefaultListModel();
        jlistapelicula.setModel(modelopeli);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        chenombrepeli = new javax.swing.JRadioButton();
        cheautorpeli = new javax.swing.JRadioButton();
        chepreciopeli = new javax.swing.JRadioButton();
        busnombrepeli = new javax.swing.JTextField();
        busaupeli = new javax.swing.JTextField();
        precio1 = new javax.swing.JTextField();
        alabelpeli = new javax.swing.JLabel();
        precio2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistapelicula = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtablepelicula = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione algún Parametro de Búsqueda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 0, -1, -1));

        chenombrepeli.setText("Nombre Pelicula");
        chenombrepeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chenombrepeliActionPerformed(evt);
            }
        });
        getContentPane().add(chenombrepeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 51, -1, -1));

        cheautorpeli.setText("Autor Pelicula");
        cheautorpeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheautorpeliActionPerformed(evt);
            }
        });
        getContentPane().add(cheautorpeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 51, -1, -1));

        chepreciopeli.setText("Precio Pelicula");
        chepreciopeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chepreciopeliActionPerformed(evt);
            }
        });
        getContentPane().add(chepreciopeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 51, -1, -1));
        getContentPane().add(busnombrepeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 76, 93, -1));
        getContentPane().add(busaupeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 76, 92, -1));
        getContentPane().add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 76, 68, -1));

        alabelpeli.setText("A");
        getContentPane().add(alabelpeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 79, -1, -1));
        getContentPane().add(precio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 76, 68, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 107, 181, -1));

        jButton2.setText("Volver a modo de Compra");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 136, 172, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel3.setText("Seleccione alguna Pelicula");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 141, -1, -1));

        jlistapelicula.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlistapelicula.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistapeliculaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlistapelicula);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 165, 188, -1));

        jButton3.setText("Parar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 177, 94, -1));

        jButton4.setText("Reproducir");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 218, 94, -1));

        jButton5.setText("Comprar");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 309, 122, -1));

        jLabel4.setText("Informacion de la Película");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 318, -1, -1));

        jtablepelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre", "Autor", "Precio"
            }
        ));
        jScrollPane3.setViewportView(jtablepelicula);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 338, -1, 106));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chepreciopeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chepreciopeliActionPerformed
        chenombrepeli.setSelected(false);
        cheautorpeli.setSelected(false);
        this.precio1.setVisible(true);
        this.precio2.setVisible(true);
        alabelpeli.setVisible(true);
        this.busnombrepeli.setVisible(false);
        this.busaupeli.setVisible(false);
    }//GEN-LAST:event_chepreciopeliActionPerformed

    private void cheautorpeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheautorpeliActionPerformed
        this.busaupeli.setVisible(true);
        chenombrepeli.setSelected(false);
        chepreciopeli.setSelected(false);
        this.precio1.setVisible(false);
        this.precio2.setVisible(false);
        alabelpeli.setVisible(false);
        this.busnombrepeli.setVisible(false);
    }//GEN-LAST:event_cheautorpeliActionPerformed

    private void chenombrepeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chenombrepeliActionPerformed

        this.busnombrepeli.setVisible(true);
        chepreciopeli.setSelected(false);
        cheautorpeli.setSelected(false);
        this.precio1.setVisible(false);
        this.precio2.setVisible(false);
        alabelpeli.setVisible(false);
        this.busaupeli.setVisible(false);
    }//GEN-LAST:event_chenombrepeliActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        Instancias insta = new Instancias();
        insta.modocompra();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Usuariocompeli peli = new Usuariocompeli();
        peli.Cargarnombre();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jlistapeliculaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistapeliculaValueChanged
        table.mostrarinfor();
    }//GEN-LAST:event_jlistapeliculaValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CompraPelicula dialog = new CompraPelicula(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alabelpeli;
    public static javax.swing.JTextField busaupeli;
    public static javax.swing.JTextField busnombrepeli;
    public static javax.swing.JRadioButton cheautorpeli;
    public static javax.swing.JRadioButton chenombrepeli;
    public static javax.swing.JRadioButton chepreciopeli;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public static javax.swing.JList<String> jlistapelicula;
    public static javax.swing.JTable jtablepelicula;
    public static javax.swing.JTextField precio1;
    public static javax.swing.JTextField precio2;
    // End of variables declaration//GEN-END:variables
}
