
package Interfaces;

import static Archivos.ArchivoCompraPelicula.cantipeli;
import Procedimientos.Instancias;
import Procedimientos.Usuariocomdisco;
import Procedimientos.procedimientodisco;
import static Procedimientos.procedimientodisco.nombre;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class CompraDisco extends javax.swing.JDialog {

    /**
     * this jframe will let you buy a cd and then is gonna do all this under the interface talking about sending emails, and saving on the file
     */
    public static DefaultListModel modelo;

    Usuariocomdisco us = new Usuariocomdisco();
    Instancias insta = new Instancias();
    procedimientodisco disco = new procedimientodisco();

    public CompraDisco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Comprar Disco");
        buscarnombre.setVisible(false);
        buscarautor.setVisible(false);
        buscarprecio.setVisible(false);
        buscarprecio2.setVisible(false);
        alabel.setVisible(false);

        modelo = new DefaultListModel();
        jlistacompradisco.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistacompradisco = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtablecompradisco = new javax.swing.JTable();
        buscarnombre = new javax.swing.JTextField();
        buscarautor = new javax.swing.JTextField();
        buscarprecio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bponer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buscarprecio2 = new javax.swing.JTextField();
        alabel = new javax.swing.JLabel();
        chepreciodisco = new javax.swing.JRadioButton();
        cheautordisco = new javax.swing.JRadioButton();
        chenombredisco = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        bparar = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione algún Parametro de Búsqueda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jlistacompradisco.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlistacompradisco.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistacompradiscoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlistacompradisco);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 151, 200, -1));

        jtablecompradisco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Autor", "Precio", "Cancion"
            }
        ));
        jScrollPane2.setViewportView(jtablecompradisco);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 100));
        getContentPane().add(buscarnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, -1));
        getContentPane().add(buscarautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 70, 100, -1));
        getContentPane().add(buscarprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 81, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 97, 170, -1));

        bponer.setText("Reproducir");
        bponer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bponerActionPerformed(evt);
            }
        });
        getContentPane().add(bponer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 98, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel2.setText("Información del Disco");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 287, -1, -1));

        jButton3.setText("Proceder a Compra");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 280, 140, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel3.setText("Seleccione algún Disco");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 131, -1, -1));
        getContentPane().add(buscarprecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 81, -1));

        alabel.setText("  A");
        getContentPane().add(alabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 70, -1, 20));

        chepreciodisco.setText("Precio Disco");
        chepreciodisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chepreciodiscoActionPerformed(evt);
            }
        });
        getContentPane().add(chepreciodisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        cheautordisco.setText("Autor Disco");
        cheautordisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheautordiscoActionPerformed(evt);
            }
        });
        getContentPane().add(cheautordisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        chenombredisco.setText("Nombre Disco");
        chenombredisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chenombrediscoActionPerformed(evt);
            }
        });
        getContentPane().add(chenombredisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jButton4.setText("Volver a Modo Compra");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, -1));

        bparar.setText("Parar");
        bparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpararActionPerformed(evt);
            }
        });
        getContentPane().add(bparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chepreciodiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chepreciodiscoActionPerformed
        chenombredisco.setSelected(false);
        cheautordisco.setSelected(false);
        this.buscarprecio.setVisible(true);
        this.buscarprecio2.setVisible(true);
        alabel.setVisible(true);
        this.buscarnombre.setVisible(false);
        this.buscarautor.setVisible(false);
    }//GEN-LAST:event_chepreciodiscoActionPerformed

    private void cheautordiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheautordiscoActionPerformed
        this.buscarautor.setVisible(true);
        chenombredisco.setSelected(false);
        chepreciodisco.setSelected(false);
        this.buscarprecio.setVisible(false);
        this.buscarprecio2.setVisible(false);
        alabel.setVisible(false);
        this.buscarnombre.setVisible(false);
    }//GEN-LAST:event_cheautordiscoActionPerformed

    private void chenombrediscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chenombrediscoActionPerformed
        this.buscarnombre.setVisible(true);
        chepreciodisco.setSelected(false);
        cheautordisco.setSelected(false);
        this.buscarprecio.setVisible(false);
        this.buscarprecio2.setVisible(false);
        alabel.setVisible(false);
        this.buscarautor.setVisible(false);
    }//GEN-LAST:event_chenombrediscoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();

        insta.modocompra();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int precio11 = 0;
        int precio22 = 0;
        try {
            precio11 = Integer.parseInt(buscarprecio.getText());
            precio22 = Integer.parseInt(buscarprecio2.getText());
        } catch (java.lang.NumberFormatException e) {
        }

        if (precio11 > precio22) {
            JOptionPane.showMessageDialog(null, "Ingrese un precio de mayor a menor!");
            buscarnombre.setText("");
            buscarautor.setText("");
            buscarprecio.setText("");
            buscarprecio2.setText("");
        } else {
            us.Cargarnombre();
            buscarnombre.setText("");
            buscarautor.setText("");
            buscarprecio.setText("");
            buscarprecio2.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jlistacompradiscoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistacompradiscoValueChanged
        us.mostrarinfor();

    }//GEN-LAST:event_jlistacompradiscoValueChanged


    private void bponerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bponerActionPerformed

        us.reproducirmusica();
    }//GEN-LAST:event_bponerActionPerformed

    private void bpararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpararActionPerformed

        us.parar();
    }//GEN-LAST:event_bpararActionPerformed

    public String cantidad() {
        String cantidad = null;
        try {
            String temp;
            BufferedReader bf2 = new BufferedReader(new FileReader("Discos.txt"));
            int contador = 0;

            temp = "";
            String bfRead;

            while ((bfRead = bf2.readLine()) != null) {
                contador++;
                temp = bfRead;
                String lista = temp;
                String[] lista1 = lista.split(";");
                if (jlistacompradisco.getSelectedValue().equals(lista1[0])) {
                    cantidad = lista1[5];

                }
            }
            bf2.close();
        } catch (IOException e) {
            System.err.println("No se encontro el archivo" + e);
        }
        return cantidad;
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (jlistacompradisco.isSelectionEmpty()) {

            JOptionPane.showMessageDialog(null, "Seleccione un Disco para Comprar!");
        }
        if (Integer.parseInt(cantidad()) <= 0) {
            this.dispose();
            disco.leercantidad();
        } else {
            this.dispose();

            insta.procesocomdisco();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alabel;
    public static javax.swing.JButton bparar;
    public static javax.swing.JButton bponer;
    public static javax.swing.JTextField buscarautor;
    public static javax.swing.JTextField buscarnombre;
    public static javax.swing.JTextField buscarprecio;
    public static javax.swing.JTextField buscarprecio2;
    public static javax.swing.JRadioButton cheautordisco;
    public static javax.swing.JRadioButton chenombredisco;
    public static javax.swing.JRadioButton chepreciodisco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JList<String> jlistacompradisco;
    public static javax.swing.JTable jtablecompradisco;
    // End of variables declaration//GEN-END:variables

}
