/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Procedimientos.Instancias;
import Procedimientos.Usuariocomdisco;
import javax.swing.DefaultListModel;

/**
 *
 * @author Kevin
 */
public class CompraDisco extends javax.swing.JDialog {

    /**
     * Creates new form CompraDisco
     */
    public static DefaultListModel modelo;
    Usuariocomdisco table = new Usuariocomdisco();
    Usuariocomdisco us = new Usuariocomdisco();

    public CompraDisco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Comprar Disco");
        buscarnombre.setVisible(false);
        buscarautor.setVisible(false);
        buscarprecio.setVisible(false);
        buscarprecio2.setVisible(false);
        alabel.setVisible(false);

        modelo = new DefaultListModel();
        jlistacompradisco.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistacompradisco = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtablecompradisco = new javax.swing.JTable();
        buscarnombre = new javax.swing.JTextField();
        buscarautor = new javax.swing.JTextField();
        buscarprecio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bponer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buscarprecio2 = new javax.swing.JTextField();
        alabel = new javax.swing.JLabel();
        chepreciodisco = new javax.swing.JRadioButton();
        cheautordisco = new javax.swing.JRadioButton();
        chenombredisco = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        bparar = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione algún Parametro de Búsqueda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jlistacompradisco.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlistacompradisco.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistacompradiscoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlistacompradisco);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 151, 200, -1));

        jtablecompradisco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Autor", "Precio", "Cancion"
            }
        ));
        jScrollPane2.setViewportView(jtablecompradisco);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 100));
        getContentPane().add(buscarnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, -1));
        getContentPane().add(buscarautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 70, 100, -1));
        getContentPane().add(buscarprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 81, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 97, 170, -1));

        bponer.setText("Reproducir");
        bponer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bponerActionPerformed(evt);
            }
        });
        getContentPane().add(bponer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 98, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel2.setText("Información del Disco");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 287, -1, -1));

        jButton3.setText("Comprar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 280, 120, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel3.setText("Seleccione algún Disco");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 131, -1, -1));
        getContentPane().add(buscarprecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 81, -1));

        alabel.setText("  A");
        getContentPane().add(alabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 70, -1, 20));

        chepreciodisco.setText("Precio Disco");
        chepreciodisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chepreciodiscoActionPerformed(evt);
            }
        });
        getContentPane().add(chepreciodisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        cheautordisco.setText("Autor Disco");
        cheautordisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheautordiscoActionPerformed(evt);
            }
        });
        getContentPane().add(cheautordisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        chenombredisco.setText("Nombre Disco");
        chenombredisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chenombrediscoActionPerformed(evt);
            }
        });
        getContentPane().add(chenombredisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jButton4.setText("Volver a Modo Compra");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, -1));

        bparar.setText("Parar");
        bparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpararActionPerformed(evt);
            }
        });
        getContentPane().add(bparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chepreciodiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chepreciodiscoActionPerformed
        chenombredisco.setSelected(false);
        cheautordisco.setSelected(false);
        this.buscarprecio.setVisible(true);
        this.buscarprecio2.setVisible(true);
        alabel.setVisible(true);
        this.buscarnombre.setVisible(false);
        this.buscarautor.setVisible(false);
    }//GEN-LAST:event_chepreciodiscoActionPerformed

    private void cheautordiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheautordiscoActionPerformed
        this.buscarautor.setVisible(true);
        chenombredisco.setSelected(false);
        chepreciodisco.setSelected(false);
        this.buscarprecio.setVisible(false);
        this.buscarprecio2.setVisible(false);
        alabel.setVisible(false);
        this.buscarnombre.setVisible(false);
    }//GEN-LAST:event_cheautordiscoActionPerformed

    private void chenombrediscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chenombrediscoActionPerformed
        this.buscarnombre.setVisible(true);
        chepreciodisco.setSelected(false);
        cheautordisco.setSelected(false);
        this.buscarprecio.setVisible(false);
        this.buscarprecio2.setVisible(false);
        alabel.setVisible(false);
        this.buscarautor.setVisible(false);
    }//GEN-LAST:event_chenombrediscoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        Instancias insta = new Instancias();
        insta.modocompra();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Usuariocomdisco user = new Usuariocomdisco();
        user.Cargarnombre();
        buscarnombre.setText("");
        buscarautor.setText("");
        buscarprecio.setText("");
        buscarprecio2.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jlistacompradiscoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistacompradiscoValueChanged
        table.mostrarinfor();

    }//GEN-LAST:event_jlistacompradiscoValueChanged


    private void bponerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bponerActionPerformed

        us.reproducirmusica();
    }//GEN-LAST:event_bponerActionPerformed

    private void bpararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpararActionPerformed

        us.parar();
    }//GEN-LAST:event_bpararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CompraDisco dialog = new CompraDisco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alabel;
    public static javax.swing.JButton bparar;
    public static javax.swing.JButton bponer;
    public static javax.swing.JTextField buscarautor;
    public static javax.swing.JTextField buscarnombre;
    public static javax.swing.JTextField buscarprecio;
    public static javax.swing.JTextField buscarprecio2;
    public static javax.swing.JRadioButton cheautordisco;
    public static javax.swing.JRadioButton chenombredisco;
    public static javax.swing.JRadioButton chepreciodisco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JList<String> jlistacompradisco;
    public static javax.swing.JTable jtablecompradisco;
    // End of variables declaration//GEN-END:variables

}
